# -*- coding: utf-8 -*-
"""Untitled38.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ovZI7f-p9sA07Sz_7jxbhwiIjHjdq0-q
"""

x=int(input("enter a 1 number"))
y= int(input("enter a 2 number"))
if y==0:
  print("Invalid")
else:
  z=x//y
  print("result",z)